```yaml
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 526983806356.dkr.ecr.ap-southeast-2.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t aws-practice1 .
      - docker tag aws-practice1:latest 526983806356.dkr.ecr.ap-southeast-2.amazonaws.com/aws-practice1:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 526983806356.dkr.ecr.ap-southeast-2.amazonaws.com/aws-practice1:latest
      - echo Docker image pushed successfully.
```
